### PR TITLE
Remove solid-start-mdx package / old docs

### PR DESCRIPTION
**Pull request by birkskyum**
I'm trying to clean up the MDX story, so it's [more clear](https://github.com/solidjs/solid-start/discussions/1149), and so solid devs can take full advantage of [recent development](https://www.npmjs.com/package/@shikijs/twoslash) with twoslash, shiki etc, and it came to my attention that solid-start-mdx has become obsolete.

solid-start-mdx is not used in the with-mdx example, or the new docs, where instead we use a combination of these three:

https://www.npmjs.com/package/solid-mdx
http://www.npmjs.com/package/@vinxi/plugin-mdx
https://www.npmjs.com/package/@mdx-js/mdx

And the solid-site repo uses:

https://www.npmjs.com/package/solid-mdx
https://www.npmjs.com/package/@mdx-js/rollup

There have also been a few community efforts in this space:

https://www.npmjs.com/package/vite-plugin-solid-markdown
https://www.npmjs.com/package/solidjs-mdx

More info about [solid-start-mdx](https://www.npmjs.com/package/solid-start-mdx):

Screenshot 2024-03-18 at 16 04 17

Screenshot 2024-03-18 at 16 04 25

### CODE REVIEW

**Comment by birkskyum** [comment]
I'll look into that one - might have missed that

**Comment by birkskyum** [comment]
Okay, so it's used exclusively in https://start.solidjs.com/ a bit longer.

**Comment by ryansolid** [comment]
Yep. That's the only reason exists. But it can go away soon.

**Comment by birkskyum** [comment]
Seems like it now would be better for new users now if the url in the start GitHub repo pointed to here where guides and api docs are updated:

https://docs.solidjs.com/solid-start

**Pull request closed without merging**
