### PR TITLE
Allow . in Netlify edge function paths

### PR DESCRIPTION
**Pull request by iainmerrick**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

When deploying as a Netlify edge function, it explicitly does not handle any paths containing a "." character.

These paths fall through to the default Netlify 404 page (not the project's own 404).

## What is the new behavior?

All requests are handled by the edge function. If the project has its own 404 page, we don't ever see the default Netlify 404.

## Other information

I've manually tested that this covers the following cases:
- static asset (with or without `.` in name)
- dynamic routes (with or without `.` in name)
- internal `fetch` of static asset (from `public`)
- internal `fetch` of dynamic route

If you'd like me to put together a test, let me know. It's not really specific to Netlify so I guess it doesn't belong in this package.

### CODE REVIEW

**Comment by iainmerrick** [comment]
Now I see what's going on; edge functions shadow static assets, so with this PR as it stands all assets will be shadowed and served as 404s by the edge function instead. I didn't notice this at first because all the assets were cached, doh.

Skipping the edge function for paths containing `.` handles most common cases pretty well, but it blocks a lot of useful legitimate usage (for example, I'd like to implement the GOPROXY protocol which necessarily uses `.`).

**Comment by iainmerrick** [comment]
I've added `"excludedPath": "/assets/*"` to the manifest, and that fixes the Vite assets.

Static files in `public` (e.g. `favicon.ico`) still don't work because they could live anywhere.

**Comment by iainmerrick** [comment]
OK! This PR now covers all the following cases:
- static asset (with or without `.` in name)
- dynamic routes (with or without `.` in name)
- internal `fetch` of static asset (from `public`)
- internal `fetch` of dynamic route

If you'd like me to put together a test, let me know. It's not really specific to Netlify so I guess the test wouldn't belong in this package.

**Comment by iainmerrick** [comment]
I had a quick look at adding a test, but it looks like:
- existing tests aren't yet run against the various adapters (including `start-netlify`);
- tests are currently failing.

**Comment by ryansolid** [comment]
I think the case I'd want to check is top level wildcard routes.. classically having star routes like we do in the Hackernews example break when we don't put some sort of criteria in.

**Comment by iainmerrick** [comment]
> I think the case I'd want to check is top level wildcard routes.. classically having star routes like we do in the Hackernews example break when we don't put some sort of criteria in.

Makes sense... I've deployed the HN sample using my solid-start-netlify branch here: https://github.com/iainmerrick/solid-start-edge-test/pull/1

Looks like it's working correctly. I'll add a few routes to test those cases I listed.

**Comment by iainmerrick** [comment]
Test routes:
- static asset: https://deploy-preview-1--solid-start-edge-test.netlify.app/favicon.ico
- redirect to asset: https://deploy-preview-1--solid-start-edge-test.netlify.app/favicon-redirect.ico
- internal fetch asset: https://deploy-preview-1--solid-start-edge-test.netlify.app/favicon-static-fetch.ico
- fetch another route: https://deploy-preview-1--solid-start-edge-test.netlify.app/favicon-dynamic-fetch.ico

**Comment by ryansolid** [comment]
Seems good to me thanks for testing

**Pull request merged**
