### PR TITLE
Missed dependency in solid-start module

### PR DESCRIPTION
**Pull request by AdvTechnoKing**
solid-start using rollup-route-manifest without rollup

image

### CODE REVIEW

**Comment by atk** [comment]
But it is using vite, which loads rollup already.

**Comment by AdvTechnoKing** [comment]
I use pnpm, which does not load modules that are already on the computer, so it only puts the modules that are specified in package.json.

**Comment by AdvTechnoKing** [comment]
It is not recommended to depend on modules of other packages, because they can be changed at any time

**Comment by atk** [comment]
> I use pnpm, which does not load modules that are already on the computer, so it only puts the modules that are specified in package.json.

Other people are using npm or yarn. It should work either way. Also, it could be a conscious decision to let vite manage the version of rollup.

**Pull request merged**
