### PR TITLE
build(with-vitest): :heavy_plus_sign: add missing dependencies

### PR DESCRIPTION
**Pull request by seahindeniz**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

When I run `pnpm test` and `pnpm coverage` in the `with-vitest` example, I get the following errors
- `Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'vite-plugin-solid'`
- `MISSING DEPENDENCY  Cannot find dependency '@vitest/coverage-v8'`

## What is the new behavior?
Without the missing required dependencies, the scripts will run as expected

### CODE REVIEW

**Comment by atk** [comment]
Original author of that template here:

If you configure coverage to be collected, the package will be automatically installed. For those who don't collect it, it's a superfluous package, which is the reason it is not installed by default.

**Comment by seahindeniz** [comment]
Hey @atk 👋. I added it because having a script to collect coverage with a missing dependency creates a bit unexpected visual for the first comer. At least that's how I felt first after trying out every script and then felt the urge to add them. First time users may even say this is a bug. 
IMHO, the choice must start from the point of creating the script, rather then starting with and error 🙏

**Comment by atk** [comment]
If that is the case then let us remove the script and add the ability to collect coverage to the documentation.

**Comment by seahindeniz** [comment]
Just removed the script and the dep. I'm not sure how you mean document it but let me know what to add and where, I can assist, or please do a commit

**Review by atk — APPROVED** [review]

**Comment by ryansolid** [comment]
Thanks

**Pull request merged**
