### PR TITLE
vite v3 upgrade: fixes https://github.com/solidjs/solid-start/issues/185

### PR DESCRIPTION
**Pull request by btakita**
Was not able to run the tests due to installing the current version of solid-start from npm. Feel free to ignore this PR if more work is needed to perform the upgrade.

### CODE REVIEW

**Comment by boehs** [comment]
Nice discovery! The tests here are failing because you need to update the .pnpm lockfile by running `pnpm install` and push that file as well. Annoying but it's the way it is!

Additionally I expect it would be preferential to merge this into the `dev` branch instead of main

**Comment by btakita** [comment]
Thank you. I did not notice the `dev` branch. I've been running my project using the `main` branch.

**Comment by nksaraf** [comment]
can you run `pnpm` install and push the updated pnpm lockfile, we need that for the tests to run properly

**Comment by btakita** [comment]
@nksaraf I updated `pnpm-lock.yaml`. Been force pushing npm package updates in the mean time.

**Comment by nksaraf** [comment]
ohh thanks for figuring this one out.. I think I can try to figure out why the tests are not passing

**Pull request merged**
