### PR TITLE
Migrate the with-authjs example

### PR DESCRIPTION
**Pull request by birkskyum**
The https://mediakit-taupe.vercel.app/auth/install appear to need a bit of attention in order to fix this, but I've fixed most of the in this branch

### CODE REVIEW

**Comment by birkskyum** [comment]
it's a quite popular solution, so it would be great to have working.
Screenshot 2024-02-03 at 13 40 48

the error i get is from the api route:

```sh
UnknownAction: Cannot parse action at /api/auth/session .Read more at https://errors.authjs.dev#unknownaction
```

**Comment by ryansolid** [comment]
How's it going? Any blockers I should know about?

**Comment by birkskyum** [comment]
I was awaiting an update to the mediakit auth package - will try this again soon when this recent commit hits a release https://github.com/solidjs-community/mediakit/commit/446e30f97b47706164bb43fe2cb0bcf78bcb55c1

**Comment by birkskyum** [comment]
@OrJDev , i keep hitting this error with server response with Discord: "{"client_id": ["Value \"undefined\" is not snowflake."]}"

have you hit that before?

**Comment by OrJDev** [comment]
> @OrJDev , i keep hitting this error with server response with Discord, even when setting the appropriate env vars: "{"client_id": ["Value \"undefined\" is not snowflake."]}"
> 
> 
> 
> have you hit that before?

Never. Im not the one who made this example, please use create jd app to create a fully working example with Solid Start & AuthJs.

```
pnpm create jd-app@latest
```

http://github.com/orjdev/create-jd-app

**Comment by OrJDev** [comment]
> I tried that just now - it gives me a repo with very old deps (auth/core, @solidjs/start, vite etc.) and after setting the discord id/secret i see this:
> 
> 
> 
> Screenshot 2024-03-11 at 17 42 54
> 
> 
> 
> 
> 
> My current redirect url is:
> 
> `http://localhost:3000/api/auth/discord/callback`

Wdym old deps? Also check out the redirect uri on the url on discord and send it here

**Comment by birkskyum** [comment]
I ran `npm create jd-app@latest` and got this:

**Comment by birkskyum** [comment]
Thanks, that did the trick! It was the callback/discord that i had swapped in the url

**Comment by birkskyum** [comment]
@ryansolid , this is ready now - I made the PR against the archived_examples folder to show the diff more clearly than moving it to the examples folder in one step, but it's good to go.

**Comment by ryansolid** [comment]
Awesome thank you

**Comment by ryansolid** [comment]
Yeah this looks way cleaner

**Comment by ryansolid** [comment]
Yeah I will merge this. Only thing I'm unclear is how this solution works with route load functions. To be fair the context provider will be available in them it is just less clear to me the patterns here.

**Pull request merged**
