### PR TITLE
fix unstable islands on windows

### PR DESCRIPTION
**Pull request by orenelbaum**
I replaced the backslashes in the windows path with forward slashes

### CODE REVIEW

**Comment by ryansolid** [comment]
I have to ask.. is doing path conversions like this our best option?

**Comment by atk** [comment]
There's no native path conversion in node, unfortunately.

**Comment by orenelbaum** [comment]
I don't know if that's how it's supposed to be done, but it seems to work on both Windows and Linux

**Comment by dev-rb** [comment]
I implemented a similar fix in the movies branch. Using the vite `normalizePath` function.
https://github.com/solidjs/solid-start/blob/movies/packages/start/islands/vite-plugin.js

**Comment by peerreynders** [comment]
> I don't know if that's how it's supposed to be done

Going by the node documentation I'd assume something like this:

```JS
// file: index.mjs
import { parse, posix, sep} from 'node:path';

const toPosix = (original) => 
  original.split(sep).join(posix.sep);

const full = process.argv[1];
const { root, dir } = parse(full);
const noRoot = dir.slice(root.length);

console.log(toPosix(full));
console.log(toPosix(dir));
console.log(toPosix(noRoot));
```

- [`path.sep`](https://nodejs.org/api/path.html#pathsep)
- [`path.posix`](https://nodejs.org/api/path.html#pathposix)

**Pull request merged**
