### PR TITLE
feat: automatic theme switching for Tailwind

### LINKED ISSUE #1563: [Feature?]: Tailwind template should come with automatic theme switching support "out-of-the-box"
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

_No response_

### Examples 🌈

_No response_

### Motivation 🔦

_No response_

### PR DESCRIPTION
**Pull request by hamirmahal**
closes #1563.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

If the system theme changes to night mode, a newly created Solid app would stay in day mode.

## What is the new behavior?
A newly created Solid app will switch themes when the system theme changes.

### CODE REVIEW

**Review by hamirmahal — COMMENTED** [review]
I'm not too sure how to add automated testing for the presence of a night theme, and correct theme switching when the system theme changes.

I'm happy to take any suggestions on that.

**Comment by hamirmahal** [comment]
# With this change

[Screencast from 06-27-2024 04:27:01 PM.webm](https://github.com/solidjs/solid-start/assets/43425812/c507437a-1341-46ef-aaa1-bc554ff81933)

**Comment by ryansolid** [comment]
I'm not too worried about the CSS in the examples compared to the functionality of the javascript. Thanks for the PR.

**Comment by hamirmahal** [comment]
You're welcome!

**Pull request merged**
