### PR TITLE
support server env variables

### PR DESCRIPTION
**Pull request by OrJDev**
.env:
```
VITE_TEST=1
SERVER_TEST=2
```
code on client:
 ```ts
  console.log("client", import.meta.env.VITE_TEST); // equals 1 - as expected
```
  
credits to https://github.com/nuxt/nuxt.js/blob/dev/packages/config/src/load.js 

code on server:
```ts
export const routeData = () => {
  return createServerData$(() => {
    // @ts-ignore
    const t = process.env.SERVER_TEST;
    console.log({ t }); // equals 2 - as expected
    return t;
  });
```
};  

closes https://github.com/solidjs/solid-start/issues/480

### CODE REVIEW

**Comment by OrJDev** [comment]
on client:

    ```const t = process.env.SERVER_TEST; // not defined - as expected```

**Comment by OrJDev** [comment]
on server:

```ts
    const s = process.env.VITE_TEST; // not defined - as expected because it was loaded on client
```

**Comment by ryansolid** [comment]
Thank you. Although not going to default bare to `ssr:false`.

**Comment by OrJDev** [comment]
Ahh yes i just hated that it prints it multiple times, ofc you can delete the entire env thing from the examples it was just to test

**Comment by apatrida** [comment]
now configure environment variables, do a production build, and see VITE ignore them at runtime as they appear that `VITE_` variables are only read and used at build time.  Above examples seem like you are only running and testing in dev mode.

**Pull request merged**
