### PR TITLE
feat: call handleRefetch() when the response is not a redirect

### PR DESCRIPTION
**Pull request by BigDog1400**
#682 
The createRouteAction.tsx, is already calling handleRefetch() when the response is not instance of Response interface.
```tsx
  .then(async data => {
        if (reqId === count) {
          if (data instanceof Response) {
            await handleResponse(data, navigate, options);
          } else await handleRefetch(data as any[], options);
          if (!data || isRedirectResponse(data)) setInput(undefined);
          else setResult({ data });
        }
        return data;
      })
      .catch(async e => {
        if (reqId === count) {
          if (e instanceof Response) {
            await handleResponse(e, navigate, options);
          }
          if (!isRedirectResponse(e)) {
            setResult({ error: e });
          } else setInput(undefined);
        }
```

When it is instance of Response, the handleResponse should call handleRefetch when it is not a redirect. I don't think it make sense to invalidate query only when is happening a redirect, should be exactly the contrary

### CODE REVIEW

**Comment by BigDog1400** [comment]
I think that actually when a redirect happens, for example in a nested route and both routes share some common parent component layout, for example a parent route with path /users, and two childrens /users/:id, users/:id/details, we might want to execute query invalidation in the route data of /users. If that is the case, the handleRefetch() might always should be executed inside the handleResponse(). Not shure about this, i haven't tried it yet

**Comment by BigDog1400** [comment]
I tested this with the nested layout case, and as expected if you have a parent route and go to another children path, it doesn't handle invalidations in the page. I guess that there is not need to check for `isRedirectResponse`, and just return the handleRefetch() always

**Comment by nksaraf** [comment]
@ryansolid might make sense to do this?

**Comment by BigDog1400** [comment]
Base on my last comment, this PR should be modify and replace this
`if (!isRedirectResponse(response)) return handleRefetch(response, options);` to this   `return handleRefetch(response, options);`, if there is no other reason to do the check in the response parameter

**Comment by ryansolid** [comment]
The original code was

```js
 if (response.ok || isRedirectResponse(response)) return handleRefetch(response, options);
```
The idea was it refetched except on error. Unclear why the response.ok was removed.

**Comment by ryansolid** [comment]
@BigDog1400 can you just update the PR with the condition removed.. I will merge and do a release.

**Comment by BigDog1400** [comment]
> @BigDog1400 can you just update the PR with the condition removed.. I will merge and do a release.

Done!

**Pull request merged**
