### PR TITLE
[Feature]: Add Server Reference to FetchEvent Type for WebSocket Communication with Socket.IO

### PR DESCRIPTION
**Pull request by aronmal**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] Tests for the changes have been added (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature #1017
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
No reference to the server for possible socket.io implementation.

## What is the new behavior?
Added reference to the the server and the type.

## Other information
#1017

### CODE REVIEW

**Comment by aronmal** [comment]
@ryansolid
I reworked the branch. Types are checked and worked for me in both vite dev and start-node mode.  Please review :wink:

**Comment by ryansolid** [comment]
This seems reasonable. Although this layer will be changing in the future so this sort of detail may be lost depending on the implementation.

**Comment by aronmal** [comment]
If the implementation is changed, I can adapt to it. But it would be nice to access the httpServer somehow to use socket.io without having to run a second node server. Thanks 😉 .

**Comment by aronmal** [comment]
When can I expect the next release?

**Pull request merged**
