### PR TITLE
feat: seroval 1.0

### PR DESCRIPTION
**Pull request by lxsmnsyc**
Re-opening for #1140

### CODE REVIEW

**Comment by ryansolid** [comment]
I'm still getting an error. 

Steps to reproduce:
1. Add new Todo
2. Check that Todo
3. Uncheck it

> [h3] [unhandled] H3Error: invariant
    at VanillaDeserializerContext.deserialize (file:///Users/ryancarniato/Development/solid-start/node_modules/.pnpm/seroval@1.0.0/node_modules/seroval/dist/esm/development/index.mjs:1880:15)
    ... 6 lines matching cause stack trace ...
    at async Server.toNodeHandle (file:///Users/ryancarniato/Development/solid-start/node_modules/.pnpm/h3@1.9.0/node_modules/h3/dist/index.mjs:1885:7) {
  cause: Error: invariant
      at VanillaDeserializerContext.deserialize (file:///Users/ryancarniato/Development/solid-start/node_modules/.pnpm/seroval@1.0.0/node_modules/seroval/dist/esm/development/index.mjs:1880:15)
      at VanillaDeserializerContext.deserializeArray (file:///Users/ryancarniato/Development/solid-start/node_modules/.pnpm/seroval@1.0.0/node_modules/seroval/dist/esm/development/index.mjs:1617:26)
      at VanillaDeserializerContext.deserialize (file:///Users/ryancarniato/Development/solid-start/node_modules/.pnpm/seroval@1.0.0/node_modules/seroval/dist/esm/development/index.mjs:1826:21)
      at Proxy.fromJSON (file:///Users/ryancarniato/Development/solid-start/node_modules/.pnpm/seroval@1.0.0/node_modules/seroval/dist/esm/development/index.mjs:3138:14)
      at handleServerFunction (/Users/ryancarniato/Development/solid-start/packages/start/config/server-handler.js:64:36)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Object.handler (file:///Users/ryancarniato/Development/solid-start/node_modules/.pnpm/h3@1.9.0/node_modules/h3/dist/index.mjs:1675:19)
      at async Server.toNodeHandle (file:///Users/ryancarniato/Development/solid-start/node_modules/.pnpm/h3@1.9.0/node_modules/h3/dist/index.mjs:1885:7),
  statusCode: 500,
  fatal: false,
  unhandled: true,
  statusMessage: undefined,
  data: undefined
}

**Comment by lxsmnsyc** [comment]
Thanks! will test again

**Comment by lxsmnsyc** [comment]
I can't seem to reproduce it

Screenshot 2023-12-20 at 12 38 20 PM

**Comment by lxsmnsyc** [comment]
Merging this to a new branch

**Pull request merged**
