### PR TITLE
Feat/add supabase example

### PR DESCRIPTION
**Pull request by caseybaggz**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
Examples doesn't have a project for showing how to integrated SS with Supabase. This has been a consistent discussion in the Discord #solid-start channel lately.

## What is the new behavior?
- Adds the new project to the examples directory

## Other information
This is an **optimistic PR** assuming [its predecessor](https://github.com/supabase/auth-helpers/pull/594) get's merged in.

### CODE REVIEW

**Comment by caseybaggz** [comment]
@ryansolid can you setup a repo and I'll knock this out? See [supabase PR for details](https://github.com/supabase/auth-helpers/pull/594)

**Review by Dezzj — COMMENTED** [review]
Veiwed

**Review by Dezzj — COMMENTED** [review]
Veiwed

**Comment by ryansolid** [comment]
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed in mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.

**Pull request closed without merging**
