### PR TITLE
fix link tags for nested routes

### LINKED ISSUE #171: CSS loaded from `root.tsx` missing for index nested routes during production SSR
Repro: https://github.com/ghalle/solid-start-index-layout-css

1. build and start
2. Go to http://localhost:3000/about

This only applies to index nested routes other than the `/` route.
This only applies if the CSS is loaded from the `root.tsx` moving it to `routes/index.tsx` fixes it.

### PR DESCRIPTION
**Pull request by ghalle**
Fixes #171 

Previously only link tags for the topmost routes were being added to the document. Now all link tags for the ancestors routes will be added. This fixes a CSS flashing issue during prod SSR for nested routes.

A check for index nested routes was also added to correctly match the manifest key, this fixes an issue where the CSS was not getting loaded at all during prod SSR for index nested routes.

### CODE REVIEW

**Comment by nksaraf** [comment]
Do you think we could have a strategy for testing this in our playwright test suite.. maybe we detect if the correct css is present based on the route you visit.. I think playwright should have the APIs for this..

Any ideas or thoughts about this?

**Comment by ghalle** [comment]
Yes as long as there is a way to check if a certain link tag is in the head of the document before any other JavaScript executes it should be fairly simple. Although I've just noticed that sometimes vite merges all the css into one `entry-client.hash.css` instead of keeping it as separate files but it seems to be deterministic so as long as we have a setup where that doesn't happen it should be fine.

**Comment by nksaraf** [comment]
We should inspect the html from a raw request itself, instead of in playwright's headless page. then no javascript executes, and we just check the html, like here: https://github.com/solidjs/solid-start/blob/25406e4ff746066b11123fb511b0d41ba2b0e12b/test/rendering-test.ts#L70

Do you think you could add tests for this in this PR?

**Comment by ghalle** [comment]
Yes, been working on it, but vite's CSS code splitting seems very unreliable, it randomly stops splitting some CSS files when I modify a completely unrelated file.

I'll try again tomorrow.

**Pull request merged**
