### PR TITLE
Upgrade to vinxi 0.5 (vite 6)

### PR DESCRIPTION
**Pull request by birkskyum**
Continuation of
- https://github.com/nksaraf/vinxi/pull/417

This updates the vinxi and vite version in the root and /packages/start.

Despite packages/start 1.0.10 using the `@vinxi` 0.4.3 packages below, it does appear to be compatible with vinxi 0.5.0, but this pr aligns it all on the same vinxi 0.5.0 version:

```
"@vinxi/plugin-directives": "^0.4.3",
"@vinxi/server-components": "^0.4.3",
"@vinxi/server-functions": "^0.4.3".
```

Examples can be updated only after the release is cut, because they don't use "workspace:*" (due to create-solid).

I tested this by building locally and updated the with-vitest example, which works for `ssr:true/false`, and `vinxi dev/build/start`

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [X] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] infrastructure changes
- [ ] Other... Please describe:

### CODE REVIEW

**Comment by ryansolid** [comment]
ok yeah.. I will do a few local tests. But lets get this minor out.

**Comment by ryansolid** [comment]
Yeah I merged this as my examples all worked. But there is definitely FOUC in dev again. Probably from latest Vinxi release. We need confirm it is coming from there I suppose.

**Comment by apatrida** [comment]
Vinxi 0.5.1 released, still FOUCing?

**Comment by birkskyum** [comment]
0.5.1 didn't FOUC, but it has issues still.

The plan is to sunset vinxi.

**Comment by rhengles** [comment]
https://discord.com/channels/722131463138705510/1319990584512876584

**Pull request merged**
