### PR TITLE
add omitNestedClosingTags to types

### PR DESCRIPTION
**Pull request by birkskyum**
Typescript is complaining about [omitNestedClosingTags](https://github.com/solidjs/solid/blob/main/CHANGELOG.md#smaller-templates) missing in vite config.

This PR might not be needed if https://github.com/solidjs/vite-plugin-solid/pull/122 is merged.

### CODE REVIEW

**Comment by birkskyum** [comment]
seems like this will be needed too. Tried installing vite-plufgin-solid 2.7.2 , with solid-start and it wasn't able to find omitNestedClosingTags

**Comment by edivados** [comment]
Hmm it's there with 2.7.2. How are you trying to set it?

```js
import solid from "solid-start/vite";
import { defineConfig } from "vite";

export default defineConfig({
  plugins: [solid({
    solid: {
      omitNestedClosingTags: true
    }
  })],
});

```

**Comment by birkskyum** [comment]
You're right, it's there under:
```ts
    solid({
      ssr: true,
      solid: {
        omitNestedClosingTags
      }
```

This PR would add it to:

```ts
    solid({
      ssr: true,
      omitNestedClosingTags
```

Turns out I'm a bit confused about the nested  `solid: { solid: {}}` 😅 can't be alone with that

**Comment by ryansolid** [comment]
It is confusing because there is a VIte plugin Solid and a separate SolidStart plugin with a solid option that passes to the Vite Plugin Solid. This weirdness goes away in the next version. I don't know.. Do the options actually pass through. If so I guess I should merge.

**Comment by birkskyum** [comment]
@edivados  Can you check if it takes effect if the omitNestedClosingTags is added to both the outer and inner solid: {} ?

**Comment by edivados** [comment]
The inner one works since it gets added to presets in vite-plugin-solid. The outer one gets passed down to vite-plugin-solid but it does nothing with it so it does not end up in dom-expressions.

**Comment by birkskyum** [comment]
Okay, thanks for checking it out.

**Comment by ryansolid** [comment]
Thanks you both. Ok. I'm going to do the release now.

**Pull request closed without merging**
